default_platform(:ios)

platform :ios do
  desc "Build and run test"
  lane :build_and_run_test do |options|
	scan
  end
desc "Discord notification"
lane :send do
  discord_notifier(
    webhook_url: ENV["WEBHOOK_URL"],
    title: "Fastlane sender",
    description: "Description",
    success: true,
    thumbnail_url:"https://cdn.discordapp.com/embed/avatars/0.png",
    image_url:"https://cdn.discordapp.com/embed/avatars/0.png",
    fields:[
      {
        name:"Field1", 
        value:"Value1"
      },
      {
        name:"Field2", 
        value:"Value2",
        inline: true
      },
      {
        name:"Field3", 
        value:"Value3",
        inline: true
      }
    ]
  )
end
end
