default_platform(:ios)

platform :ios do

    desc "Build for testing"
    lane build_for_testing do |options|
        scan
    end
    
    desc "Run test from derived data"
    lane tests_run do |options|
        run_tests(
            derived_data_path: "my_folder",
            test_without_building: true
        )
    end
    
    desc "Build and test from building folder"
    lane build_and_test do |options|
        build_for_testing
        tests_run
    end
    
    desc "Build and run test"
    lane :build_and_run_test do |options|
        scan
    end
    desc "Discord notification"
    lane :send do
      discord_notifier(
        webhook_url: ENV["WEBHOOK_URL"],
        title: "Fastlane sender",
        description: "Description",
        success: true,
        thumbnail_url:"https://cdn.discordapp.com/embed/avatars/0.png",
        image_url:"https://cdn.discordapp.com/embed/avatars/0.png",
        fields:[
          {
            name:"Field1",
            value:"Value1"
          },
          {
            name:"Field2",
            value:"Value2",
            inline: true
          },
          {
            name:"Field3",
            value:"Value3",
            inline: true
          }
        ]
      )
    end
end
