name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Send start notification to Discord
      uses: appleboy/discord-action@master
      with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#8b9b9c"
          username: "GitHub Bot"
          message: |
            Tests started by 👤 ${{ github.actor }}
            From `${{ github.head_ref }}` to `${{ github.base_ref }}`
            Event `${{ github.event_name }}`
            PR ${{ github.event.number }}: ${{ github.event.pull_request.url }}
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Build and Run
      run: |
        bundle exec fastlane build_and_run_test
 
